### ISSUE TITLE
StartupPage not loading with latest Xamarin.Forms 5

### ISSUE THREAD

**Issue by tylerwilson** [DamirsCorner/20201030-xamarin-forms-shell-login#2]
I downloaded, built and ran as-is from source, which uses Xamarin.Forms 4.8, and it ran fine as expected.

I updated to Xamarin.Forms 5 (also updated Xamarin Essentials), and ran again, and it goes directly to Login page without going through the StartupPage CheckLogin code.

Thank you.

**Comment by damirarh** [comment]
Adding StartupPage the same way as LoginPage fixes this issue.
